CREATE DATABASE mjc813_db CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER 'lys'@'%' IDENTIFIED BY 'lys0723^^';
GRANT ALL PRIVILEGES ON mjc813_db.* TO 'lys'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;